apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: factory
  namespace: manuela-stormshift-messaging
  labels:
    strimzi.io/cluster: factory-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: factory-cluster
  namespace: manuela-stormshift-messaging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: route
        tls: true
        configuration:
          bootstrap:
            host: bootstrap-factory-kafka-cluster.{{ .Values.global.localClusterDomain }}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
