kind: ConfigMap
apiVersion: v1
metadata:
  name: mqtt2kafka-config
  namespace: manuela-stormshift-messaging
data:
  application.properties: |
    kafka.broker.uri={{ .Values.kafka.broker.uri }}
    kafka.broker.topic.temperature={{ .Values.kafka.broker.topic.temperature }}
    kafka.broker.topic.vibration={{ .Values.kafka.broker.topic.vibration }}

    mqtt.broker.uri={{ .Values.mqtt.broker.uri }}
    mqtt.broker.clientId={{ .Values.mqtt.broker.clientId }}
    mqtt.broker.topic.temperature={{ .Values.mqtt.broker.topic.temperature }}
    mqtt.broker.topic.vibration={{ .Values.mqtt.broker.topic.vibration }}

    local.cluster.name={{ .Values.global.localClusterDomain }}
    s3.region=none
